dependencies:
- name: demo-deepu
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.12
- name: spring-boot-rest-prometheus
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
